"""schema v3.6 (outbox)

Revision ID: 88bcb519e391
Revises: 
Create Date: 2026-05-21 15:49:40.230034
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


revision: str = '88bcb519e391'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('festival',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('sales_start_on', sa.Date(), nullable=False),
    sa.Column('starts_on', sa.Date(), nullable=False),
    sa.Column('ends_on', sa.Date(), nullable=False),
    sa.Column('timezone', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email_verified', sa.Boolean(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('role', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('consent_at', sa.DateTime(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=False),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', sa.DateTime(), nullable=True),
    sa.Column('telegram_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('archetype',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'key', name='uq_archetype')
    )
    op.create_index(op.f('ix_archetype_festival_id'), 'archetype', ['festival_id'], unique=False)
    op.create_table('artist',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_special', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'name', name='uq_artist')
    )
    op.create_index(op.f('ix_artist_festival_id'), 'artist', ['festival_id'], unique=False)
    op.create_table('author',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'name', name='uq_author')
    )
    op.create_index(op.f('ix_author_festival_id'), 'author', ['festival_id'], unique=False)
    op.create_table('authtoken',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_authtoken_token'), 'authtoken', ['token'], unique=True)
    op.create_index(op.f('ix_authtoken_user_id'), 'authtoken', ['user_id'], unique=False)
    op.create_table('festivalday',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('day', sa.Date(), nullable=False),
    sa.Column('first_concert_at', sa.DateTime(), nullable=True),
    sa.Column('last_concert_at', sa.DateTime(), nullable=True),
    sa.Column('last_concert_ends_at', sa.DateTime(), nullable=True),
    sa.Column('concert_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'day', name='uq_festivalday')
    )
    op.create_index(op.f('ix_festivalday_festival_id'), 'festivalday', ['festival_id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'name', name='uq_genre')
    )
    op.create_index(op.f('ix_genre_festival_id'), 'genre', ['festival_id'], unique=False)
    op.create_table('hall',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('address', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('lat', sa.Float(), nullable=True),
    sa.Column('lon', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'name', name='uq_hall_festival_name')
    )
    op.create_index(op.f('ix_hall_festival_id'), 'hall', ['festival_id'], unique=False)
    op.create_table('outboxmessage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('payload', sa.JSON(), nullable=True),
    sa.Column('scheduled_for', sa.DateTime(), nullable=False),
    sa.Column('status', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(), nullable=True),
    sa.Column('idempotency_key', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_outboxmessage_idempotency_key'), 'outboxmessage', ['idempotency_key'], unique=True)
    op.create_index(op.f('ix_outboxmessage_user_id'), 'outboxmessage', ['user_id'], unique=False)
    op.create_table('program',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('signature', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'signature', name='uq_program')
    )
    op.create_index(op.f('ix_program_festival_id'), 'program', ['festival_id'], unique=False)
    op.create_table('routesheet',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_routesheet_festival_id'), 'routesheet', ['festival_id'], unique=False)
    op.create_index(op.f('ix_routesheet_user_id'), 'routesheet', ['user_id'], unique=False)
    op.create_table('simstate',
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('availability_mode', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('festival_id')
    )
    op.create_table('userpreferences',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('pace', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('interest_vector', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('available_days', sa.JSON(), nullable=True),
    sa.Column('time_windows', sa.JSON(), nullable=True),
    sa.Column('favorite_author_ids', sa.JSON(), nullable=True),
    sa.Column('favorite_genre_ids', sa.JSON(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'festival_id')
    )
    op.create_table('usersession',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('token', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_usersession_token'), 'usersession', ['token'], unique=True)
    op.create_index(op.f('ix_usersession_user_id'), 'usersession', ['user_id'], unique=False)
    op.create_table('composition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('author_id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['author_id'], ['author.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'author_id', 'title', name='uq_composition')
    )
    op.create_index(op.f('ix_composition_author_id'), 'composition', ['author_id'], unique=False)
    op.create_index(op.f('ix_composition_festival_id'), 'composition', ['festival_id'], unique=False)
    op.create_table('concert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('show_num', sa.Integer(), nullable=False),
    sa.Column('crm_show_id', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('hall_id', sa.Integer(), nullable=False),
    sa.Column('festival_day_id', sa.Integer(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=False),
    sa.Column('duration_min', sa.Integer(), nullable=False),
    sa.Column('price_kopecks', sa.Integer(), nullable=False),
    sa.Column('is_family_friendly', sa.Boolean(), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('program_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['festival_day_id'], ['festivalday.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['program_id'], ['program.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'show_num', name='uq_concert_shownum')
    )
    op.create_index(op.f('ix_concert_crm_show_id'), 'concert', ['crm_show_id'], unique=False)
    op.create_index(op.f('ix_concert_festival_day_id'), 'concert', ['festival_day_id'], unique=False)
    op.create_index(op.f('ix_concert_festival_id'), 'concert', ['festival_id'], unique=False)
    op.create_index(op.f('ix_concert_hall_id'), 'concert', ['hall_id'], unique=False)
    op.create_index(op.f('ix_concert_program_id'), 'concert', ['program_id'], unique=False)
    op.create_index(op.f('ix_concert_show_num'), 'concert', ['show_num'], unique=False)
    op.create_table('dayroute',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('festival_day_id', sa.Integer(), nullable=False),
    sa.Column('archetype_id', sa.Integer(), nullable=True),
    sa.Column('concerts_count', sa.Integer(), nullable=False),
    sa.Column('halls_count', sa.Integer(), nullable=False),
    sa.Column('show_minutes', sa.Integer(), nullable=False),
    sa.Column('transition_minutes', sa.Integer(), nullable=False),
    sa.Column('wait_minutes', sa.Integer(), nullable=False),
    sa.Column('cost_kopecks', sa.Integer(), nullable=False),
    sa.Column('hall_changes', sa.Integer(), nullable=False),
    sa.Column('comfort_score', sa.Float(), nullable=False),
    sa.Column('diversity_score', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['archetype_id'], ['archetype.id'], ),
    sa.ForeignKeyConstraint(['festival_day_id'], ['festivalday.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dayroute_archetype_id'), 'dayroute', ['archetype_id'], unique=False)
    op.create_index(op.f('ix_dayroute_festival_day_id'), 'dayroute', ['festival_day_id'], unique=False)
    op.create_index(op.f('ix_dayroute_festival_id'), 'dayroute', ['festival_id'], unique=False)
    op.create_table('halltransition',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('from_hall_id', sa.Integer(), nullable=False),
    sa.Column('to_hall_id', sa.Integer(), nullable=False),
    sa.Column('minutes', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['from_hall_id'], ['hall.id'], ),
    sa.ForeignKeyConstraint(['to_hall_id'], ['hall.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'from_hall_id', 'to_hall_id', name='uq_transition')
    )
    op.create_index(op.f('ix_halltransition_festival_id'), 'halltransition', ['festival_id'], unique=False)
    op.create_index(op.f('ix_halltransition_from_hall_id'), 'halltransition', ['from_hall_id'], unique=False)
    op.create_index(op.f('ix_halltransition_to_hall_id'), 'halltransition', ['to_hall_id'], unique=False)
    op.create_table('offprogram',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('external_num', sa.Integer(), nullable=True),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('starts_at', sa.DateTime(), nullable=True),
    sa.Column('duration_min', sa.Integer(), nullable=True),
    sa.Column('hall_id', sa.Integer(), nullable=True),
    sa.Column('fmt', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_recommended', sa.Boolean(), nullable=False),
    sa.Column('link', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.ForeignKeyConstraint(['hall_id'], ['hall.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_offprogram_festival_id'), 'offprogram', ['festival_id'], unique=False)
    op.create_table('availabilitysnapshot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('at', sa.DateTime(), nullable=False),
    sa.Column('tickets_left', sa.Integer(), nullable=True),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_availabilitysnapshot_at'), 'availabilitysnapshot', ['at'], unique=False)
    op.create_index(op.f('ix_availabilitysnapshot_concert_id'), 'availabilitysnapshot', ['concert_id'], unique=False)
    op.create_table('concertartist',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artist.id'], ),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('concert_id', 'artist_id')
    )
    op.create_table('concertavailability',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('is_on_sale', sa.Boolean(), nullable=False),
    sa.Column('tickets_left', sa.Integer(), nullable=True),
    sa.Column('source', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('concert_id')
    )
    op.create_table('concertcomposition',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('composition_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['composition_id'], ['composition.id'], ),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.PrimaryKeyConstraint('concert_id', 'composition_id')
    )
    op.create_table('concertgenre',
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ),
    sa.PrimaryKeyConstraint('concert_id', 'genre_id')
    )
    op.create_table('dayrouteconcert',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('day_route_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['day_route_id'], ['dayroute.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('day_route_id', 'concert_id', name='uq_dayrouteconcert')
    )
    op.create_index(op.f('ix_dayrouteconcert_concert_id'), 'dayrouteconcert', ['concert_id'], unique=False)
    op.create_index(op.f('ix_dayrouteconcert_day_route_id'), 'dayrouteconcert', ['day_route_id'], unique=False)
    op.create_table('purchase',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('festival_id', sa.Integer(), nullable=False),
    sa.Column('external_op_id', sa.Integer(), nullable=False),
    sa.Column('customer_external_id', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('purchased_at', sa.DateTime(), nullable=False),
    sa.Column('price_kopecks', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['festival_id'], ['festival.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('festival_id', 'external_op_id', name='uq_purchase_op')
    )
    op.create_index(op.f('ix_purchase_concert_id'), 'purchase', ['concert_id'], unique=False)
    op.create_index(op.f('ix_purchase_customer_external_id'), 'purchase', ['customer_external_id'], unique=False)
    op.create_index(op.f('ix_purchase_external_op_id'), 'purchase', ['external_op_id'], unique=False)
    op.create_index(op.f('ix_purchase_festival_id'), 'purchase', ['festival_id'], unique=False)
    op.create_table('routesheetitem',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('route_sheet_id', sa.Integer(), nullable=False),
    sa.Column('concert_id', sa.Integer(), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['concert_id'], ['concert.id'], ),
    sa.ForeignKeyConstraint(['route_sheet_id'], ['routesheet.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('route_sheet_id', 'concert_id', name='uq_sheetitem')
    )
    op.create_index(op.f('ix_routesheetitem_concert_id'), 'routesheetitem', ['concert_id'], unique=False)
    op.create_index(op.f('ix_routesheetitem_route_sheet_id'), 'routesheetitem', ['route_sheet_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_routesheetitem_route_sheet_id'), table_name='routesheetitem')
    op.drop_index(op.f('ix_routesheetitem_concert_id'), table_name='routesheetitem')
    op.drop_table('routesheetitem')
    op.drop_index(op.f('ix_purchase_festival_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_external_op_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_customer_external_id'), table_name='purchase')
    op.drop_index(op.f('ix_purchase_concert_id'), table_name='purchase')
    op.drop_table('purchase')
    op.drop_index(op.f('ix_dayrouteconcert_day_route_id'), table_name='dayrouteconcert')
    op.drop_index(op.f('ix_dayrouteconcert_concert_id'), table_name='dayrouteconcert')
    op.drop_table('dayrouteconcert')
    op.drop_table('concertgenre')
    op.drop_table('concertcomposition')
    op.drop_table('concertavailability')
    op.drop_table('concertartist')
    op.drop_index(op.f('ix_availabilitysnapshot_concert_id'), table_name='availabilitysnapshot')
    op.drop_index(op.f('ix_availabilitysnapshot_at'), table_name='availabilitysnapshot')
    op.drop_table('availabilitysnapshot')
    op.drop_index(op.f('ix_offprogram_festival_id'), table_name='offprogram')
    op.drop_table('offprogram')
    op.drop_index(op.f('ix_halltransition_to_hall_id'), table_name='halltransition')
    op.drop_index(op.f('ix_halltransition_from_hall_id'), table_name='halltransition')
    op.drop_index(op.f('ix_halltransition_festival_id'), table_name='halltransition')
    op.drop_table('halltransition')
    op.drop_index(op.f('ix_dayroute_festival_id'), table_name='dayroute')
    op.drop_index(op.f('ix_dayroute_festival_day_id'), table_name='dayroute')
    op.drop_index(op.f('ix_dayroute_archetype_id'), table_name='dayroute')
    op.drop_table('dayroute')
    op.drop_index(op.f('ix_concert_show_num'), table_name='concert')
    op.drop_index(op.f('ix_concert_program_id'), table_name='concert')
    op.drop_index(op.f('ix_concert_hall_id'), table_name='concert')
    op.drop_index(op.f('ix_concert_festival_id'), table_name='concert')
    op.drop_index(op.f('ix_concert_festival_day_id'), table_name='concert')
    op.drop_index(op.f('ix_concert_crm_show_id'), table_name='concert')
    op.drop_table('concert')
    op.drop_index(op.f('ix_composition_festival_id'), table_name='composition')
    op.drop_index(op.f('ix_composition_author_id'), table_name='composition')
    op.drop_table('composition')
    op.drop_index(op.f('ix_usersession_user_id'), table_name='usersession')
    op.drop_index(op.f('ix_usersession_token'), table_name='usersession')
    op.drop_table('usersession')
    op.drop_table('userpreferences')
    op.drop_table('simstate')
    op.drop_index(op.f('ix_routesheet_user_id'), table_name='routesheet')
    op.drop_index(op.f('ix_routesheet_festival_id'), table_name='routesheet')
    op.drop_table('routesheet')
    op.drop_index(op.f('ix_program_festival_id'), table_name='program')
    op.drop_table('program')
    op.drop_index(op.f('ix_outboxmessage_user_id'), table_name='outboxmessage')
    op.drop_index(op.f('ix_outboxmessage_idempotency_key'), table_name='outboxmessage')
    op.drop_table('outboxmessage')
    op.drop_index(op.f('ix_hall_festival_id'), table_name='hall')
    op.drop_table('hall')
    op.drop_index(op.f('ix_genre_festival_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_festivalday_festival_id'), table_name='festivalday')
    op.drop_table('festivalday')
    op.drop_index(op.f('ix_authtoken_user_id'), table_name='authtoken')
    op.drop_index(op.f('ix_authtoken_token'), table_name='authtoken')
    op.drop_table('authtoken')
    op.drop_index(op.f('ix_author_festival_id'), table_name='author')
    op.drop_table('author')
    op.drop_index(op.f('ix_artist_festival_id'), table_name='artist')
    op.drop_table('artist')
    op.drop_index(op.f('ix_archetype_festival_id'), table_name='archetype')
    op.drop_table('archetype')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('festival')
    # ### end Alembic commands ###
